<?php

declare(strict_types=1);

/*
 * SampleAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SampleAPILib\Tests\Controllers;

use SampleAPILib\Controllers\APIController;
use SampleAPILib\Exceptions;

class APIControllerTest extends BaseTestController
{
    /**
     * @var APIController APIController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getAPIController();
    }

    public function testGetAListOfItems()
    {
        // Perform API call
        $result = null;
        try {
            $result = self::$controller->getAListOfItems();
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->allowExtraHeaders()->expectHeaders($headers)->assert();
    }
}
