<?php

declare(strict_types=1);

/*
 * SampleAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SampleAPILib\Tests;

use Core\Types\CallbackCatcher;
use SampleAPILib\SampleAPIClient;
use SampleAPILib\SampleAPIClientBuilder;

class ClientFactory
{
    public static function create(CallbackCatcher $httpCallback): SampleAPIClient
    {
        $clientBuilder = SampleAPIClientBuilder::init();
        $clientBuilder = self::addConfigurationFromEnvironment($clientBuilder);
        $clientBuilder = self::addTestConfiguration($clientBuilder);
        return $clientBuilder->httpCallback($httpCallback)->build();
    }

    public static function addTestConfiguration(SampleAPIClientBuilder $builder): SampleAPIClientBuilder
    {
        return $builder;
    }

    public static function addConfigurationFromEnvironment(SampleAPIClientBuilder $builder): SampleAPIClientBuilder
    {
        $timeout = getenv('SAMPLE_API_LIB_TIMEOUT');
        $numberOfRetries = getenv('SAMPLE_API_LIB_NUMBER_OF_RETRIES');
        $maximumRetryWaitTime = getenv('SAMPLE_API_LIB_MAXIMUM_RETRY_WAIT_TIME');
        $environment = getenv('SAMPLE_API_LIB_ENVIRONMENT');

        if (!empty($timeout) && \is_numeric($timeout)) {
            $builder->timeout(intval($timeout));
        }

        if (!empty($numberOfRetries) && \is_numeric($numberOfRetries)) {
            $builder->numberOfRetries(intval($numberOfRetries));
        }

        if (!empty($maximumRetryWaitTime) && \is_numeric($maximumRetryWaitTime)) {
            $builder->maximumRetryWaitTime(intval($maximumRetryWaitTime));
        }

        if (!empty($environment)) {
            $builder->environment($environment);
        }

        return $builder;
    }
}
