<?php

declare(strict_types=1);

/*
 * SampleAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SampleAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SampleAPILib\Models\Details;
use SampleAPILib\Models\Specifications;

/**
 * Builder for model Details
 *
 * @see Details
 */
class DetailsBuilder
{
    /**
     * @var Details
     */
    private $instance;

    private function __construct(Details $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Details Builder object.
     */
    public static function init(): self
    {
        return new self(new Details());
    }

    /**
     * Sets manufacturer field.
     *
     * @param string|null $value
     */
    public function manufacturer(?string $value): self
    {
        $this->instance->setManufacturer($value);
        return $this;
    }

    /**
     * Sets warranty field.
     *
     * @param string|null $value
     */
    public function warranty(?string $value): self
    {
        $this->instance->setWarranty($value);
        return $this;
    }

    /**
     * Sets specifications field.
     *
     * @param Specifications|null $value
     */
    public function specifications(?Specifications $value): self
    {
        $this->instance->setSpecifications($value);
        return $this;
    }

    /**
     * Initializes a new Details object.
     */
    public function build(): Details
    {
        return CoreHelper::clone($this->instance);
    }
}
