<?php

declare(strict_types=1);

/*
 * SampleAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SampleAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SampleAPILib\Models\Details;
use SampleAPILib\Models\Item;
use SampleAPILib\Models\Pricing;
use SampleAPILib\Models\Pricing1;
use SampleAPILib\Models\Pricing2;
use SampleAPILib\Models\Pricing3;
use SampleAPILib\Models\Pricing4;
use SampleAPILib\Models\Pricing5;
use SampleAPILib\Models\Pricing6;

/**
 * Builder for model Item
 *
 * @see Item
 */
class ItemBuilder
{
    /**
     * @var Item
     */
    private $instance;

    private function __construct(Item $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Item Builder object.
     */
    public static function init(): self
    {
        return new self(new Item());
    }

    /**
     * Sets id field.
     *
     * @param int|null $value
     */
    public function id(?int $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets value field.
     *
     * @param int|null $value
     */
    public function value(?int $value): self
    {
        $this->instance->setValue($value);
        return $this;
    }

    /**
     * Sets tags field.
     *
     * @param string[]|null $value
     */
    public function tags(?array $value): self
    {
        $this->instance->setTags($value);
        return $this;
    }

    /**
     * Sets metadata field.
     *
     * @param array<string,string>|null $value
     */
    public function metadata(?array $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Sets details field.
     *
     * @param Details|null $value
     */
    public function details(?Details $value): self
    {
        $this->instance->setDetails($value);
        return $this;
    }

    /**
     * Sets status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets pricing field.
     *
     * @param Pricing|Pricing1|Pricing2|Pricing3|Pricing4|Pricing5|Pricing6|null $value
     */
    public function pricing($value): self
    {
        $this->instance->setPricing($value);
        return $this;
    }

    /**
     * Initializes a new Item object.
     */
    public function build(): Item
    {
        return CoreHelper::clone($this->instance);
    }
}
