<?php

declare(strict_types=1);

/*
 * SampleAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SampleAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SampleAPILib\Models\Item;
use SampleAPILib\Models\ItemsResponse;

/**
 * Builder for model ItemsResponse
 *
 * @see ItemsResponse
 */
class ItemsResponseBuilder
{
    /**
     * @var ItemsResponse
     */
    private $instance;

    private function __construct(ItemsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Items Response Builder object.
     */
    public static function init(): self
    {
        return new self(new ItemsResponse());
    }

    /**
     * Sets items field.
     *
     * @param Item[]|null $value
     */
    public function items(?array $value): self
    {
        $this->instance->setItems($value);
        return $this;
    }

    /**
     * Initializes a new Items Response object.
     */
    public function build(): ItemsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
