<?php

declare(strict_types=1);

/*
 * SampleAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SampleAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SampleAPILib\Models\Pricing77;

/**
 * Builder for model Pricing77
 *
 * @see Pricing77
 */
class Pricing77Builder
{
    /**
     * @var Pricing77
     */
    private $instance;

    private function __construct(Pricing77 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Pricing 77 Builder object.
     */
    public static function init(): self
    {
        return new self(new Pricing77());
    }

    /**
     * Sets price field.
     *
     * @param float|null $value
     */
    public function price(?float $value): self
    {
        $this->instance->setPrice($value);
        return $this;
    }

    /**
     * Sets currency field.
     *
     * @param string|null $value
     */
    public function currency(?string $value): self
    {
        $this->instance->setCurrency($value);
        return $this;
    }

    /**
     * Sets discount field.
     *
     * @param float|null $value
     */
    public function discount(?float $value): self
    {
        $this->instance->setDiscount($value);
        return $this;
    }

    /**
     * Sets valid Until field.
     *
     * @param \DateTime|null $value
     */
    public function validUntil(?\DateTime $value): self
    {
        $this->instance->setValidUntil($value);
        return $this;
    }

    /**
     * Sets tax field.
     *
     * @param float|null $value
     */
    public function tax(?float $value): self
    {
        $this->instance->setTax($value);
        return $this;
    }

    /**
     * Sets tax Rate field.
     *
     * @param float|null $value
     */
    public function taxRate(?float $value): self
    {
        $this->instance->setTaxRate($value);
        return $this;
    }

    /**
     * Sets membership Fee field.
     *
     * @param float|null $value
     */
    public function membershipFee(?float $value): self
    {
        $this->instance->setMembershipFee($value);
        return $this;
    }

    /**
     * Sets validity Period field.
     *
     * @param \DateTime|null $value
     */
    public function validityPeriod(?\DateTime $value): self
    {
        $this->instance->setValidityPeriod($value);
        return $this;
    }

    /**
     * Sets shipping Cost field.
     *
     * @param float|null $value
     */
    public function shippingCost(?float $value): self
    {
        $this->instance->setShippingCost($value);
        return $this;
    }

    /**
     * Sets shipping Method field.
     *
     * @param string|null $value
     */
    public function shippingMethod(?string $value): self
    {
        $this->instance->setShippingMethod($value);
        return $this;
    }

    /**
     * Sets service Charge field.
     *
     * @param float|null $value
     */
    public function serviceCharge(?float $value): self
    {
        $this->instance->setServiceCharge($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets installment field.
     *
     * @param float|null $value
     */
    public function installment(?float $value): self
    {
        $this->instance->setInstallment($value);
        return $this;
    }

    /**
     * Sets payment Due field.
     *
     * @param \DateTime|null $value
     */
    public function paymentDue(?\DateTime $value): self
    {
        $this->instance->setPaymentDue($value);
        return $this;
    }

    /**
     * Initializes a new Pricing 77 object.
     */
    public function build(): Pricing77
    {
        return CoreHelper::clone($this->instance);
    }
}
