<?php

declare(strict_types=1);

/*
 * SampleAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SampleAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SampleAPILib\Models\Pricing;

/**
 * Builder for model Pricing
 *
 * @see Pricing
 */
class PricingBuilder
{
    /**
     * @var Pricing
     */
    private $instance;

    private function __construct(Pricing $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Pricing Builder object.
     */
    public static function init(): self
    {
        return new self(new Pricing());
    }

    /**
     * Sets price field.
     *
     * @param float|null $value
     */
    public function price(?float $value): self
    {
        $this->instance->setPrice($value);
        return $this;
    }

    /**
     * Sets currency field.
     *
     * @param string|null $value
     */
    public function currency(?string $value): self
    {
        $this->instance->setCurrency($value);
        return $this;
    }

    /**
     * Initializes a new Pricing object.
     */
    public function build(): Pricing
    {
        return CoreHelper::clone($this->instance);
    }
}
