<?php

declare(strict_types=1);

/*
 * SampleAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SampleAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SampleAPILib\Models\Pricing5;

/**
 * Builder for model Pricing5
 *
 * @see Pricing5
 */
class Pricing5Builder
{
    /**
     * @var Pricing5
     */
    private $instance;

    private function __construct(Pricing5 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Pricing 5 Builder object.
     */
    public static function init(): self
    {
        return new self(new Pricing5());
    }

    /**
     * Sets service Charge field.
     *
     * @param float|null $value
     */
    public function serviceCharge(?float $value): self
    {
        $this->instance->setServiceCharge($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Initializes a new Pricing 5 object.
     */
    public function build(): Pricing5
    {
        return CoreHelper::clone($this->instance);
    }
}
