<?php

declare(strict_types=1);

/*
 * SampleAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SampleAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SampleAPILib\Models\Pricing4;

/**
 * Builder for model Pricing4
 *
 * @see Pricing4
 */
class Pricing4Builder
{
    /**
     * @var Pricing4
     */
    private $instance;

    private function __construct(Pricing4 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Pricing 4 Builder object.
     */
    public static function init(): self
    {
        return new self(new Pricing4());
    }

    /**
     * Sets shipping Cost field.
     *
     * @param float|null $value
     */
    public function shippingCost(?float $value): self
    {
        $this->instance->setShippingCost($value);
        return $this;
    }

    /**
     * Sets shipping Method field.
     *
     * @param string|null $value
     */
    public function shippingMethod(?string $value): self
    {
        $this->instance->setShippingMethod($value);
        return $this;
    }

    /**
     * Initializes a new Pricing 4 object.
     */
    public function build(): Pricing4
    {
        return CoreHelper::clone($this->instance);
    }
}
