<?php

declare(strict_types=1);

/*
 * SampleAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SampleAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SampleAPILib\Models\Pricing1;

/**
 * Builder for model Pricing1
 *
 * @see Pricing1
 */
class Pricing1Builder
{
    /**
     * @var Pricing1
     */
    private $instance;

    private function __construct(Pricing1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Pricing 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new Pricing1());
    }

    /**
     * Sets discount field.
     *
     * @param float|null $value
     */
    public function discount(?float $value): self
    {
        $this->instance->setDiscount($value);
        return $this;
    }

    /**
     * Sets valid Until field.
     *
     * @param \DateTime|null $value
     */
    public function validUntil(?\DateTime $value): self
    {
        $this->instance->setValidUntil($value);
        return $this;
    }

    /**
     * Initializes a new Pricing 1 object.
     */
    public function build(): Pricing1
    {
        return CoreHelper::clone($this->instance);
    }
}
