<?php

declare(strict_types=1);

/*
 * SampleAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SampleAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SampleAPILib\Models\Pricing6;

/**
 * Builder for model Pricing6
 *
 * @see Pricing6
 */
class Pricing6Builder
{
    /**
     * @var Pricing6
     */
    private $instance;

    private function __construct(Pricing6 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Pricing 6 Builder object.
     */
    public static function init(): self
    {
        return new self(new Pricing6());
    }

    /**
     * Sets installment field.
     *
     * @param float|null $value
     */
    public function installment(?float $value): self
    {
        $this->instance->setInstallment($value);
        return $this;
    }

    /**
     * Sets payment Due field.
     *
     * @param \DateTime|null $value
     */
    public function paymentDue(?\DateTime $value): self
    {
        $this->instance->setPaymentDue($value);
        return $this;
    }

    /**
     * Initializes a new Pricing 6 object.
     */
    public function build(): Pricing6
    {
        return CoreHelper::clone($this->instance);
    }
}
