<?php

declare(strict_types=1);

/*
 * SampleAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SampleAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SampleAPILib\Models\Pricing3;

/**
 * Builder for model Pricing3
 *
 * @see Pricing3
 */
class Pricing3Builder
{
    /**
     * @var Pricing3
     */
    private $instance;

    private function __construct(Pricing3 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Pricing 3 Builder object.
     */
    public static function init(): self
    {
        return new self(new Pricing3());
    }

    /**
     * Sets membership Fee field.
     *
     * @param float|null $value
     */
    public function membershipFee(?float $value): self
    {
        $this->instance->setMembershipFee($value);
        return $this;
    }

    /**
     * Sets validity Period field.
     *
     * @param \DateTime|null $value
     */
    public function validityPeriod(?\DateTime $value): self
    {
        $this->instance->setValidityPeriod($value);
        return $this;
    }

    /**
     * Initializes a new Pricing 3 object.
     */
    public function build(): Pricing3
    {
        return CoreHelper::clone($this->instance);
    }
}
