<?php

declare(strict_types=1);

/*
 * SampleAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SampleAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use SampleAPILib\Models\Specifications;

/**
 * Builder for model Specifications
 *
 * @see Specifications
 */
class SpecificationsBuilder
{
    /**
     * @var Specifications
     */
    private $instance;

    private function __construct(Specifications $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Specifications Builder object.
     */
    public static function init(): self
    {
        return new self(new Specifications());
    }

    /**
     * Sets weight field.
     *
     * @param float|null $value
     */
    public function weight(?float $value): self
    {
        $this->instance->setWeight($value);
        return $this;
    }

    /**
     * Sets dimensions field.
     *
     * @param string|null $value
     */
    public function dimensions(?string $value): self
    {
        $this->instance->setDimensions($value);
        return $this;
    }

    /**
     * Sets material field.
     *
     * @param string|null $value
     */
    public function material(?string $value): self
    {
        $this->instance->setMaterial($value);
        return $this;
    }

    /**
     * Initializes a new Specifications object.
     */
    public function build(): Specifications
    {
        return CoreHelper::clone($this->instance);
    }
}
