<?php

declare(strict_types=1);

/*
 * SampleAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SampleAPILib\Controllers;

use Core\Request\Parameters\BodyParam;
use Core\Request\Parameters\HeaderParam;
use CoreInterfaces\Core\Request\RequestMethod;
use SampleAPILib\Exceptions\ApiException;
use SampleAPILib\Models\ItemsRequest;
use SampleAPILib\Models\ItemsResponse;

class APIController extends BaseController
{
    /**
     * @return ItemsResponse Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function getAListOfItems(): ItemsResponse
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::GET, '/items');

        $_resHandler = $this->responseHandler()->type(ItemsResponse::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * @param ItemsRequest $body
     *
     * @return void Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function createANewItem(ItemsRequest $body): void
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/items')
            ->parameters(HeaderParam::init('Content-Type', 'application/json'), BodyParam::init($body));

        $this->execute($_reqBuilder);
    }
}
