<?php

declare(strict_types=1);

/*
 * SampleAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SampleAPILib\Models;

use SampleAPILib\ApiHelper;
use stdClass;

class Details implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $manufacturer;

    /**
     * @var string|null
     */
    private $warranty;

    /**
     * @var Specifications|null
     */
    private $specifications;

    /**
     * Returns Manufacturer.
     */
    public function getManufacturer(): ?string
    {
        return $this->manufacturer;
    }

    /**
     * Sets Manufacturer.
     *
     * @maps manufacturer
     */
    public function setManufacturer(?string $manufacturer): void
    {
        $this->manufacturer = $manufacturer;
    }

    /**
     * Returns Warranty.
     */
    public function getWarranty(): ?string
    {
        return $this->warranty;
    }

    /**
     * Sets Warranty.
     *
     * @maps warranty
     */
    public function setWarranty(?string $warranty): void
    {
        $this->warranty = $warranty;
    }

    /**
     * Returns Specifications.
     */
    public function getSpecifications(): ?Specifications
    {
        return $this->specifications;
    }

    /**
     * Sets Specifications.
     *
     * @maps specifications
     */
    public function setSpecifications(?Specifications $specifications): void
    {
        $this->specifications = $specifications;
    }

    /**
     * Converts the Details object to a human-readable string representation.
     *
     * @return string The string representation of the Details object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Details',
            [
                'manufacturer' => $this->manufacturer,
                'warranty' => $this->warranty,
                'specifications' => $this->specifications
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->manufacturer)) {
            $json['manufacturer']   = $this->manufacturer;
        }
        if (isset($this->warranty)) {
            $json['warranty']       = $this->warranty;
        }
        if (isset($this->specifications)) {
            $json['specifications'] = $this->specifications;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
