<?php

declare(strict_types=1);

/*
 * SampleAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SampleAPILib\Models;

use SampleAPILib\ApiHelper;
use SampleAPILib\Utils\DateTimeHelper;
use stdClass;

class Pricing77 implements \JsonSerializable
{
    /**
     * @var float|null
     */
    private $price;

    /**
     * @var string|null
     */
    private $currency;

    /**
     * @var float|null
     */
    private $discount;

    /**
     * @var \DateTime|null
     */
    private $validUntil;

    /**
     * @var float|null
     */
    private $tax;

    /**
     * @var float|null
     */
    private $taxRate;

    /**
     * @var float|null
     */
    private $membershipFee;

    /**
     * @var \DateTime|null
     */
    private $validityPeriod;

    /**
     * @var float|null
     */
    private $shippingCost;

    /**
     * @var string|null
     */
    private $shippingMethod;

    /**
     * @var float|null
     */
    private $serviceCharge;

    /**
     * @var string|null
     */
    private $description;

    /**
     * @var float|null
     */
    private $installment;

    /**
     * @var \DateTime|null
     */
    private $paymentDue;

    /**
     * Returns Price.
     */
    public function getPrice(): ?float
    {
        return $this->price;
    }

    /**
     * Sets Price.
     *
     * @maps price
     */
    public function setPrice(?float $price): void
    {
        $this->price = $price;
    }

    /**
     * Returns Currency.
     */
    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    /**
     * Sets Currency.
     *
     * @maps currency
     */
    public function setCurrency(?string $currency): void
    {
        $this->currency = $currency;
    }

    /**
     * Returns Discount.
     */
    public function getDiscount(): ?float
    {
        return $this->discount;
    }

    /**
     * Sets Discount.
     *
     * @maps discount
     */
    public function setDiscount(?float $discount): void
    {
        $this->discount = $discount;
    }

    /**
     * Returns Valid Until.
     */
    public function getValidUntil(): ?\DateTime
    {
        return $this->validUntil;
    }

    /**
     * Sets Valid Until.
     *
     * @maps validUntil
     * @factory \SampleAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setValidUntil(?\DateTime $validUntil): void
    {
        $this->validUntil = $validUntil;
    }

    /**
     * Returns Tax.
     */
    public function getTax(): ?float
    {
        return $this->tax;
    }

    /**
     * Sets Tax.
     *
     * @maps tax
     */
    public function setTax(?float $tax): void
    {
        $this->tax = $tax;
    }

    /**
     * Returns Tax Rate.
     */
    public function getTaxRate(): ?float
    {
        return $this->taxRate;
    }

    /**
     * Sets Tax Rate.
     *
     * @maps taxRate
     */
    public function setTaxRate(?float $taxRate): void
    {
        $this->taxRate = $taxRate;
    }

    /**
     * Returns Membership Fee.
     */
    public function getMembershipFee(): ?float
    {
        return $this->membershipFee;
    }

    /**
     * Sets Membership Fee.
     *
     * @maps membershipFee
     */
    public function setMembershipFee(?float $membershipFee): void
    {
        $this->membershipFee = $membershipFee;
    }

    /**
     * Returns Validity Period.
     */
    public function getValidityPeriod(): ?\DateTime
    {
        return $this->validityPeriod;
    }

    /**
     * Sets Validity Period.
     *
     * @maps validityPeriod
     * @factory \SampleAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setValidityPeriod(?\DateTime $validityPeriod): void
    {
        $this->validityPeriod = $validityPeriod;
    }

    /**
     * Returns Shipping Cost.
     */
    public function getShippingCost(): ?float
    {
        return $this->shippingCost;
    }

    /**
     * Sets Shipping Cost.
     *
     * @maps shippingCost
     */
    public function setShippingCost(?float $shippingCost): void
    {
        $this->shippingCost = $shippingCost;
    }

    /**
     * Returns Shipping Method.
     */
    public function getShippingMethod(): ?string
    {
        return $this->shippingMethod;
    }

    /**
     * Sets Shipping Method.
     *
     * @maps shippingMethod
     */
    public function setShippingMethod(?string $shippingMethod): void
    {
        $this->shippingMethod = $shippingMethod;
    }

    /**
     * Returns Service Charge.
     */
    public function getServiceCharge(): ?float
    {
        return $this->serviceCharge;
    }

    /**
     * Sets Service Charge.
     *
     * @maps serviceCharge
     */
    public function setServiceCharge(?float $serviceCharge): void
    {
        $this->serviceCharge = $serviceCharge;
    }

    /**
     * Returns Description.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Installment.
     */
    public function getInstallment(): ?float
    {
        return $this->installment;
    }

    /**
     * Sets Installment.
     *
     * @maps installment
     */
    public function setInstallment(?float $installment): void
    {
        $this->installment = $installment;
    }

    /**
     * Returns Payment Due.
     */
    public function getPaymentDue(): ?\DateTime
    {
        return $this->paymentDue;
    }

    /**
     * Sets Payment Due.
     *
     * @maps paymentDue
     * @factory \SampleAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setPaymentDue(?\DateTime $paymentDue): void
    {
        $this->paymentDue = $paymentDue;
    }

    /**
     * Converts the Pricing77 object to a human-readable string representation.
     *
     * @return string The string representation of the Pricing77 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Pricing77',
            [
                'price' => $this->price,
                'currency' => $this->currency,
                'discount' => $this->discount,
                'validUntil' => $this->validUntil,
                'tax' => $this->tax,
                'taxRate' => $this->taxRate,
                'membershipFee' => $this->membershipFee,
                'validityPeriod' => $this->validityPeriod,
                'shippingCost' => $this->shippingCost,
                'shippingMethod' => $this->shippingMethod,
                'serviceCharge' => $this->serviceCharge,
                'description' => $this->description,
                'installment' => $this->installment,
                'paymentDue' => $this->paymentDue
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->price)) {
            $json['price']          = $this->price;
        }
        if (isset($this->currency)) {
            $json['currency']       = $this->currency;
        }
        if (isset($this->discount)) {
            $json['discount']       = $this->discount;
        }
        if (isset($this->validUntil)) {
            $json['validUntil']     = DateTimeHelper::toRfc3339DateTime($this->validUntil);
        }
        if (isset($this->tax)) {
            $json['tax']            = $this->tax;
        }
        if (isset($this->taxRate)) {
            $json['taxRate']        = $this->taxRate;
        }
        if (isset($this->membershipFee)) {
            $json['membershipFee']  = $this->membershipFee;
        }
        if (isset($this->validityPeriod)) {
            $json['validityPeriod'] = DateTimeHelper::toRfc3339DateTime($this->validityPeriod);
        }
        if (isset($this->shippingCost)) {
            $json['shippingCost']   = $this->shippingCost;
        }
        if (isset($this->shippingMethod)) {
            $json['shippingMethod'] = $this->shippingMethod;
        }
        if (isset($this->serviceCharge)) {
            $json['serviceCharge']  = $this->serviceCharge;
        }
        if (isset($this->description)) {
            $json['description']    = $this->description;
        }
        if (isset($this->installment)) {
            $json['installment']    = $this->installment;
        }
        if (isset($this->paymentDue)) {
            $json['paymentDue']     = DateTimeHelper::toRfc3339DateTime($this->paymentDue);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
