<?php

declare(strict_types=1);

/*
 * SampleAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SampleAPILib\Models;

use SampleAPILib\ApiHelper;
use stdClass;

class Specifications implements \JsonSerializable
{
    /**
     * @var float|null
     */
    private $weight;

    /**
     * @var string|null
     */
    private $dimensions;

    /**
     * @var string|null
     */
    private $material;

    /**
     * Returns Weight.
     */
    public function getWeight(): ?float
    {
        return $this->weight;
    }

    /**
     * Sets Weight.
     *
     * @maps weight
     */
    public function setWeight(?float $weight): void
    {
        $this->weight = $weight;
    }

    /**
     * Returns Dimensions.
     */
    public function getDimensions(): ?string
    {
        return $this->dimensions;
    }

    /**
     * Sets Dimensions.
     *
     * @maps dimensions
     */
    public function setDimensions(?string $dimensions): void
    {
        $this->dimensions = $dimensions;
    }

    /**
     * Returns Material.
     */
    public function getMaterial(): ?string
    {
        return $this->material;
    }

    /**
     * Sets Material.
     *
     * @maps material
     */
    public function setMaterial(?string $material): void
    {
        $this->material = $material;
    }

    /**
     * Converts the Specifications object to a human-readable string representation.
     *
     * @return string The string representation of the Specifications object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Specifications',
            ['weight' => $this->weight, 'dimensions' => $this->dimensions, 'material' => $this->material]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->weight)) {
            $json['weight']     = $this->weight;
        }
        if (isset($this->dimensions)) {
            $json['dimensions'] = $this->dimensions;
        }
        if (isset($this->material)) {
            $json['material']   = $this->material;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
