<?php

declare(strict_types=1);

/*
 * SampleAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SampleAPILib;

/**
 * Environments available for API
 */
class Environment
{
    public const PRODUCTION = 'production';
}
